export const MOBILE_NUMBER_SUBMIT_REQUESTED = 'mobileNumber/MOBILE_NUMBER_SUBMIT_REQUESTED';
export const MOBILE_NUMBER_SUBMIT_FAILED = 'mobileNumber/MOBILE_NUMBER_SUBMIT_FAILED';
export const MOBILE_NUMBER_SUBMIT_SUCCESS = 'mobileNumber/MOBILE_NUMBER_SUBMIT_SUCCESS';
export const PROCEED_TO_OTP_VERIFICATION = 'mobileNumber/PROCEED_TO_OTP_VERIFICATION';
