export const OTP_REQUESTED = 'validateOtp/OTP_REQUESTED';
export const OTP_REQUEST_FAILED = 'validateOtp/OTP_REQUEST_FAILED';
export const OTP_REQUEST_SUCCESS = 'validateOtp/OTP_REQUEST_SUCCESS';
export const OTP_VALIDATION_REQUESTED = 'validateOtp/OTP_VALIDATION_REQUESTED';
export const OTP_VALIDATION_SUCCESS = 'validateOtp/OTP_VALIDATION_SUCCESS';
export const OTP_VALIDATION_FAILED = 'validateOtp/OTP_VALIDATION_FAILED';
